package com.zhuc.cxf.wsdl2java.t1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2013-12-13T15:55:21.234+08:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://server.t1.cxf.zhuc.com/", name = "IHelloServices")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloServices {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getHelloWords", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.GetHelloWords")
    @WebMethod
    @ResponseWrapper(localName = "getHelloWordsResponse", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.GetHelloWordsResponse")
    public java.util.List<java.lang.String> getHelloWords();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.SayHelloResponse")
    public com.zhuc.cxf.wsdl2java.t1.HashMap sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createUser2", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.CreateUser2")
    @WebMethod
    @ResponseWrapper(localName = "createUser2Response", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.CreateUser2Response")
    public com.zhuc.cxf.wsdl2java.t1.User createUser2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.zhuc.cxf.wsdl2java.t1.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.CreateUser")
    @WebMethod
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://server.t1.cxf.zhuc.com/", className = "com.zhuc.cxf.wsdl2java.t1.CreateUserResponse")
    public com.zhuc.cxf.wsdl2java.t1.User createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.String> arg2
    );
}
